.TH nn 1 nn\-VERSION
.SH NAME
nn \- simple note management
.SH SYNOPSIS
.B nn
.RB [ action ]
.SH DESCRIPTION
nn is a terminal-based simple note management tool, which helps to organize
your notes easily.
.P
t.b.d.
.SH OPTIONS
.TP
.B init
initializes a new notes directory
.TP
.B help
prints the help.
